"""Tests for the M2 upload + book-detail endpoints.

Uses an in-memory SQLite DB (already configured by tests/conftest.py) and
the Celery eager-mode fixture so the extract_pdf task runs synchronously.
We submit a small but real PDF generated by PyMuPDF so the full upload
→ extract → chapter-detect path runs without mocks.
"""

from __future__ import annotations

import io

import fitz  # type: ignore[import-untyped]


def _make_pdf_bytes(pages: list[str]) -> bytes:
    doc = fitz.open()
    for text in pages:
        page = doc.new_page()
        page.insert_text((72, 72), text)
    buf = io.BytesIO()
    doc.save(buf)
    doc.close()
    return buf.getvalue()


def test_upload_accepts_pdf_and_creates_book(client) -> None:
    pdf_bytes = _make_pdf_bytes([
        "Chapter 1\nFirst chapter body text.\n\nMore text.",
        "Chapter 2\nSecond chapter body.",
    ])

    response = client.post(
        "/api/books",
        files={"file": ("test.pdf", pdf_bytes, "application/pdf")},
    )

    assert response.status_code == 202, response.text
    body = response.json()
    assert body["title"] == "test"
    assert body["status"] in {"uploaded", "extracting", "ready"}
    assert body["detail_url"].endswith(f"/books/{body['id']}")


def test_upload_rejects_non_pdf(client) -> None:
    response = client.post(
        "/api/books",
        files={"file": ("notes.txt", b"plain text content", "text/plain")},
    )
    assert response.status_code == 415


def test_upload_rejects_empty_file(client) -> None:
    response = client.post(
        "/api/books",
        files={"file": ("empty.pdf", b"", "application/pdf")},
    )
    assert response.status_code == 400


def test_get_book_returns_chapters_after_extraction(client) -> None:
    pdf_bytes = _make_pdf_bytes([
        "Chapter 1\nFirst body.\n\nChapter 2\nSecond body.\n\nChapter 3\nThird body.",
    ])

    upload = client.post(
        "/api/books",
        files={"file": ("book.pdf", pdf_bytes, "application/pdf")},
    )
    assert upload.status_code == 202
    book_id = upload.json()["id"]

    # Eager mode means extract_pdf ran synchronously inside the POST handler.
    detail = client.get(f"/api/books/{book_id}")
    assert detail.status_code == 200
    body = detail.json()
    assert body["id"] == book_id
    assert body["status"] == "ready"
    assert len(body["chapters"]) >= 1
    # The synthetic PDF uses regex-detectable headings.
    assert body["chapters"][0]["detection_strategy"] in {"toc", "regex", "heading_lines", "fallback"}


def test_book_detail_page_renders(client) -> None:
    pdf_bytes = _make_pdf_bytes(["Just one page of body text here."])
    upload = client.post(
        "/api/books",
        files={"file": ("book.pdf", pdf_bytes, "application/pdf")},
    )
    book_id = upload.json()["id"]

    response = client.get(f"/books/{book_id}")
    assert response.status_code == 200
    assert "book" in response.text.lower() or "chapters" in response.text.lower()


def test_get_unknown_book_returns_404(client) -> None:
    response = client.get("/api/books/99999")
    assert response.status_code == 404
